#index:
#    path: /
#    controller: App\Controller\DefaultController::index

start:
  path: /v1/game
  controller: App\Controller\GameController::start
  methods: [POST]

moveBot:
  path: /v1/game/{gameId}/move/bot
  controller: App\Controller\MoveController::moveBot
  methods: [GET]

moveHuman:
  path: /v1/game/{gameId}/move/human
  controller: App\Controller\MoveController::moveHuman
  methods: [POST]